services:


  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=passwordRedis
    networks:
      - makarabanknet

volumes:
  data:

networks:
  makarabanknet:
